# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/itchyny/gojq
%global goipath         github.com/itchyny/gojq
Version:                0.12.6

%gometa

%global goname gojq

%global common_description %{expand:
Pure Go implementation of jq.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Pure Go implementation of jq

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  go-rpm-macros

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/cmd/%{name} %{goipath}/cmd/%{name}

%install
%gopkginstall
install -m 0755 -vd                           %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/cmd/%{name} %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CHANGELOG.md README.md
%{_bindir}/%{name}

%gopkgfiles

%changelog
%autochangelog
