# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/itchyny/gojq
%global goipath         github.com/itchyny/gojq
Version:                0.12.6

%gometa

%global common_description %{expand:
Pure Go implementation of jq.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README.md

Name:           gojq
Release:        %autorelease
Summary:        Pure Go implementation of jq

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/itchyny/timefmt-go)
BuildRequires:  golang(github.com/mattn/go-isatty)
BuildRequires:  golang(github.com/mattn/go-runewidth)
BuildRequires:  golang(gopkg.in/yaml.v3)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/google/go-cmp/cmp)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/cmd/%{name} %{goipath}/cmd/%{name}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CHANGELOG.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
