# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/itchyny/go-flags
%global goipath         github.com/itchyny/go-flags
Version:                1.5.0

%gometa

%global common_description %{expand:
A fork version of https://github.com/jessevdk/go-flags.}

%global golicenses      LICENSE
%global godocs          examples README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A fork version of https://github.com/jessevdk/go-flags

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/sys/unix)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Sep 28 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 1.5.0-1
- Initial package

