# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/itchyny/timefmt-go
%global goipath         github.com/itchyny/timefmt-go
Version:                0.1.3

%gometa

%global common_description %{expand:
Efficient time formatting library (strftime, strptime) for Golang.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Efficient time formatting library (strftime, strptime) for Golang

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Sep 26 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 0.1.3-1
- Initial package

