# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/cli/shurcooL-graphql
%global goipath         github.com/cli/shurcooL-graphql
Version:                0
%global tag             named-queries-declarative
%global commit          53d29f0eb7f5f1838b5f4f137b215e19bb10a5c9

%gometa

%global common_description %{expand:
Package graphql provides a GraphQL client implementation.}

%global golicenses      LICENSE
%global godocs          example README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Package graphql provides a GraphQL client implementation

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/graph-gophers/graphql-go)
#BuildRequires:  golang(github.com/graph-gophers/graphql-go/example/starwars)
BuildRequires:  golang(github.com/graph-gophers/graphql-go/relay)
BuildRequires:  golang(github.com/shurcooL/graphql)
BuildRequires:  golang(github.com/shurcooL/graphql/ident)
BuildRequires:  golang(github.com/shurcooL/graphql/internal/jsonutil)
BuildRequires:  golang(golang.org/x/net/context/ctxhttp)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Sep 28 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 0-1.20210928git53d29f0
- Initial package

