# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/AlecAivazis/survey
%global goipath         github.com/AlecAivazis/survey/v2
Version:                2.3.2

%gometa

%global common_description %{expand:
A golang library for building interactive and accessible prompts with full
support for windows and posix terminals.}

%global golicenses      LICENSE terminal/LICENSE.txt
%global godocs          examples CONTRIBUTING.md README.md terminal/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A golang library for building interactive and accessible prompts with full support for windows and posix terminals

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/kballard/go-shellquote)
BuildRequires:  golang(github.com/mgutz/ansi)
BuildRequires:  golang(golang.org/x/term)
BuildRequires:  golang(golang.org/x/text/width)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/hinshun/vt10x)
BuildRequires:  golang(github.com/kr/pty)
BuildRequires:  golang(github.com/Netflix/go-expect)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck -d .
%endif

%gopkgfiles

%changelog
* Sun Sep 26 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 2.3.2-1
- Initial package

