# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/itchyny/astgen-go
%global goipath         github.com/itchyny/astgen-go
%global commit          cc8fccf6f972f7b535bd462839bbb6aa688ef5a9

%gometa

%global common_description %{expand:
Build Go code from arbitrary value in Go.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Build Go code from arbitrary value in Go.

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Sep 26 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 0-0.1.20210926gitcc8fccf
- Initial package

