# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/muesli/reflow
%global goipath         github.com/muesli/reflow
Version:                0.3.0

%gometa

%global common_description %{expand:
A collection of (ANSI-sequence aware) text reflow operations & algorithms.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A collection of (ANSI-sequence aware) text reflow operations & algorithms

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/mattn/go-runewidth)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Sep 26 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 0.3.0-1
- Initial package

