# Generated by go2rpm 1.3
%bcond_without check
%global debug_package %{nil}

# https://github.com/gabriel-vasile/mimetype
%global goipath         github.com/gabriel-vasile/mimetype
Version:                1.4.0

%gometa

%global common_description %{expand:
A package for detecting MIME types and extensions based on magic numbers.}

%global golicenses      LICENSE
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md CHANGELOG.md\\\
                        EXAMPLES.md README.md supported_mimes.md

Name:           %{goname}
Release:        %autorelease
Summary:        Fast golang library for MIME type and file extension detection

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
