# Generated by go2rpm 1.9.0
%bcond_with check
%global debug_package %{nil}

# https://github.com/cli/crypto
%global goipath         github.com/cli/crypto
%global commit          6be313f59b03fc6cb3202011232cd2ebeeb57c6f

%gometa -f


%global common_description %{expand:
GitHub's golang-crypto fork.}

%global golicenses      PATENTS LICENSE
%global godocs          AUTHORS CONTRIBUTING.md README.md CONTRIBUTORS

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        GitHub's golang-crypto fork

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

rm -rf acme argon2 bcrypt blake2b blake2s blowfish bn256 cast5 chacha20 chacha20poly1305 cryptobyte curve25519 ed25519 hkdf md4 nacl ocsp openpgp otr pbkdf2 pkcs12 poly1305 ripemd160 salsa20 scrypt sha3 tea twofish xtea xts

sed -i "s|golang.org/x/crypto|github.com/cli/crypto|" $(find . -name "*.go" -type f)

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
