%global debug_package %{nil}

# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/charmbracelet/glamour
%global goipath         github.com/charmbracelet/glamour
Version:                0.3.0

%gometa

%global common_description %{expand:
Stylesheet-based markdown rendering for your CLI apps.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Stylesheet-based markdown rendering for your CLI apps

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}
# merged - change tests because of reflow v0.3.0
Patch0001:      https://github.com/charmbracelet/glamour/commit/ea285ca64f6ea5c179861581b01433902ecd1fd1.patch

BuildRequires:  go-rpm-macros

%description
%{common_description}

%gopkg

%prep
%goprep
%patch0001 -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
