%global debug_package %{nil}

# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/cli/oauth
%global goipath         github.com/cli/oauth
Version:                0.9.0

%gometa

%global common_description %{expand:
A library for performing OAuth Device flow and Web application flow in Go
client apps.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Library for performing OAuth Device and Web application flow

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  go-rpm-macros

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
